CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR(50) NOT NULL,
	fullname VARCHAR(100) NOT NULL,
	balance NUMERIC(10, 2) DEFAULT 0 NOT NULL,
	currency VARCHAR(5) DEFAULT 'IDR' NOT NULL,
	key CHAR(32) UNIQUE NOT NULL,
	password VARCHAR(255),
	slug VARCHAR(10) UNIQUE,
	image VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP
);
